server:
  port: 8080
  servlet:
    context-path: /secure
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/Secure?currentSchema=public
    username: postgres
    password: Serg673093
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
